global:
  scrape_interval: 15s # Intervalo de tiempo para el scraping

scrape_configs:
  - job_name: "microservices"
    static_configs:
      - targets: ["server:9090"]
      - targets: ["cliente:9091"]
    metrics_path: "/api/v1/metrics" # Nueva ruta para el scraping
